### ISSUE TITLE
Connection attempt should mean allowing a returning connection

### ISSUE THREAD

**Issue by staltz** [staltz/ssb-conn-firewall#2]
Assume both Alice and Bob have ssb-conn-firewall, rejectBlocked=true, rejectUnknown=true.

If Alice tries to connect to Bob, but Alice is a stranger to him, then Bob's conn-firewall will disallow that connection attempt. But from this point onwards, Alice should allow **receiving** connections from Bob, because she signalled that she wanted the connection.

Maybe this could be implemented just in-memory (not persisted) and last a temporary duration. E.g. If Alice tried to connect **to Bob**, then for the next 5min she also allows connections **from Bob**.

**Comment by Powersource** [comment]
Probably another issue but sort of related: if Bob follows Alice (but not the other way around) and she tries to connect to him, she still can't. Once this #2 issue is fixed this other issue would also solve itself though I think, since if Bob follows her then he'll try to connect to her and if it's within the 5min, she'll allow it.

**Comment by staltz** [comment]
>  if Bob follows Alice (but not the other way around) and she tries to connect to him, she still can't.

Hmm, this should be supported already with the released version of ssb-conn-firewall. I could make a test for it also, sounds easy.

**Comment by staltz** [comment]
Here is a test that it's supported: https://github.com/staltz/ssb-conn-firewall/commit/10c6f7669b26f0f560e6d66c7f4f9628248a1267

**Comment by staltz** [comment]
Implemented! https://github.com/staltz/ssb-conn-firewall/commit/125df8b8801ab388cd43228eac511ca76b58fcea

**Comment by Powersource** [comment]
> Here is a test that it's supported

Doesn't seem to work for me when running the latest manyverse release on phone and 9f077228c5cfd63c3d83aed6daac884b7c80b46a on desktop, and following the phone from desktop, connecting to the desktop from phone. No big deal now that #2 is solved but it feels like it could be a sign of something deeper/weird.
